apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: aksregistery640.azurecr.io/my-aks-devops:$(Build.BuildId)-latest # Replace with your ACR and image details
        ports:
        - containerPort: 80
